name: Java CI with Code Coverage

on:
  push:
    branches:
      - feat/CS-36689-compare-merge-branch
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean package

      - name: Run Tests with JaCoCo
        run: mvn jacoco:prepare-agent jacoco:report

      - name: Publish JaCoCo Report
        uses: dawidd6/action-jacoco-publish@v1

      - name: Fail if Coverage Below Threshold
        id: coverage_check
        run: |
          total_lines=$(xmllint --xpath 'string(//counter[@type="LINE"]/@covered)' target/site/jacoco/jacoco.xml)
          total_lines=${total_lines:-0}
          total_missed=$(xmllint --xpath 'string(//counter[@type="LINE"]/@missed)' target/site/jacoco/jacoco.xml)
          total_missed=${total_missed:-0}
          total_percentage=$(awk "BEGIN { pc=100*${total_lines}/${total_lines} } { printf \"%f\", pc }")
          echo "::set-output name=coverage_percentage::$total_percentage"
          if (( $(bc <<< "$total_percentage < 70.0") )); then
            echo "Coverage is below 80% - failing the build."
            exit 1
          fi

      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: target/site/jacoco
