name: Coverage report

on:
  push:
    branches:
      - feat/CS-36689-compare-merge-branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: JaCoCo Code Coverage Report
        id: jacoco_reporter
        uses: actions/setup-java@v3
        with:
          coverage_results_path: site/jococo/index.html
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 80
          fail_below_threshold: false
          publish_only_summary: false

      # Publish Coverage Job Summary (Optional)
      - name: Add Coverage Job Summary
        run: echo "${{ steps.jacoco_reporter.outputs.coverageSummary }}" >> $GITHUB_STEP_SUMMARY

      # Uploads the coverage-report.md artifact (Optional)
      - name: Upload Code Coverage Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report-markdown
          path: "coverage-report.md"
          retention-days: 1
