name: Java CI with Code Coverage

on:
  push:
    branches:
      - feat/CS-36689-compare-merge-branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean package

      - name: Run Tests with JaCoCo
        run: mvn jacoco:prepare-agent jacoco:report

      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: target/site/jacoco
