name: Publish package to the Maven Central Repository and GitHub Packages

on:
  push:
    branches:
      - feat/CS-36689-compare-merge-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_TOKEN }}

      - name: Configure settings.xml
        run: |
          mkdir -p $HOME/.m2
          echo "<settings><servers><server><id>deployment</id><username>\${env.OSSRH_USERNAME}</username><password>\${env.OSSRH_PASSWORD}</password></server></servers></settings>" > $HOME/.m2/settings.xml

      - name: Publish to the Maven Central Repository
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

#      - name: Import GPG private key
      #        run: |
      #          echo "$GPG_PRIVATE_KEY" > private.key
      #          gpg --batch --import private.key

      - name: Maven deploy with GPG signing
        run: |
          mvn clean deploy -P release
        env:
          DEPLOY_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          DEPLOY_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Publish to GitHub Packages
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}